# Generated by Django 5.2.7 on 2025-10-28 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loanapplications', '0002_alter_loanapplication_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanapplication',
            name='term_months',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
