# Generated by Django 5.2.7 on 2025-10-28 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loanapplications', '0003_alter_loanapplication_term_months'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanapplication',
            name='monthly_payment',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
    ]
