# Generated by Django 5.2.7 on 2025-10-28 08:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('loanaccounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterestLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('calculation_date', models.DateField()),
                ('interest_type', models.CharField(max_length=50)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interest_logs', to='loanaccounts.loanaccount')),
            ],
            options={
                'verbose_name': 'Interest Log',
                'ordering': ['-calculation_date'],
            },
        ),
    ]
