# Generated by Django 5.2.7 on 2025-10-28 09:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('loanaccounts', '0002_loanaccount_total_amount_paid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RepaymentSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('due_date', models.DateField()),
                ('principal_due', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('interest_due', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_due', models.DecimalField(decimal_places=2, max_digits=15)),
                ('payment_type', models.CharField(choices=[('principal', 'Principal'), ('interest', 'Interest'), ('both', 'Principal + Interest')], max_length=20)),
                ('is_paid', models.BooleanField(default=False)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('paid_date', models.DateField(blank=True, null=True)),
                ('loan_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repayment_schedule', to='loanaccounts.loanaccount')),
            ],
            options={
                'ordering': ['due_date'],
                'unique_together': {('loan_account', 'due_date')},
            },
        ),
    ]
