# Generated by Django 5.2.7 on 2025-10-28 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loanaccounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanaccount',
            name='total_amount_paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='loanaccount',
            name='total_interest_accrued',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='loanaccount',
            name='total_principal_paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
