# Generated by Django 5.2.7 on 2025-10-26 17:13

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoanProduct',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('name', models.CharField(max_length=500, unique=True)),
                ('interest_rate', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('interest_type', models.CharField(choices=[('flat', 'Flat Rate (Simple on Original Principal)'), ('diminishing', 'Diminishing Balance (Simple on Reducing Principal)'), ('compound', 'Compound Interest'), ('capitalized', 'Capitalized Interest')], max_length=50)),
                ('interest_period', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('annually', 'Annually')], default='Monthly', help_text='How interest is calculated', max_length=50)),
                ('calculation_schedule', models.CharField(choices=[('fixed', 'Fixed Calendar (e.g., 1st of month)'), ('relative', 'Relative to Loan Start Date'), ('flexible', 'Custom/Flexible Schedule')], default='relative', help_text='Defines when interest is calculated (fixed calendar, loan start date, or custom).', max_length=20)),
                ('compounding_frequency', models.PositiveIntegerField(blank=True, default=1, help_text='For compound/capitalized: Times per period to compound.', null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('currency', models.CharField(default='KES', max_length=3)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Loan Product',
                'verbose_name_plural': 'Loan Products',
                'ordering': ['-created_at'],
            },
        ),
    ]
